
for i in 0...100 {
    var hasPrefix = false
    
    if i % 2 == 0 {
        hasPrefix = true
    }
    defer {
        if hasPrefix {
            print("I have a prefix \(i)")
        }
    }
    
    
}

//[
    //{
        //"id": 38904472,
        //"name": "alcatraz-packages",
        //"full_name": "SwiftBlogDe/alcatraz-packages",
        //"owner": {
            //"login": "SwiftBlogDe",
            //"id": 7798434,
            //"avatar_url": "https://avatars.githubusercontent.com/u/7798434?v=3",
            //"gravatar_id": "",
            //"url": "https://api.github.com/users/SwiftBlogDe",
            //"html_url": "https://github.com/SwiftBlogDe",
            //"followers_url": "https://api.github.com/users/SwiftBlogDe/followers",
            //"following_url": "https://api.github.com/users/SwiftBlogDe/following{/other_user}",
            //"gists_url": "https://api.github.com/users/SwiftBlogDe/gists{/gist_id}",
            //"starred_url": "https://api.github.com/users/SwiftBlogDe/starred{/owner}{/repo}",
            //"subscriptions_url": "https://api.github.com/users/SwiftBlogDe/subscriptions",
            //"organizations_url": "https://api.github.com/users/SwiftBlogDe/orgs",
            //"repos_url": "https://api.github.com/users/SwiftBlogDe/repos",
            //"events_url": "https://api.github.com/users/SwiftBlogDe/events{/privacy}",
            //"received_events_url": "https://api.github.com/users/SwiftBlogDe/received_events",
            //"type": "Organization",
            //"site_admin": false
        //},
        //"private": false,
        //"html_url": "https://github.com/SwiftBlogDe/alcatraz-packages",
        //"description": "Package list repository for Alcatraz",
        //"fork": true,
        //"url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages",
        //"forks_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/forks",
        //"keys_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/keys{/key_id}",
        //"collaborators_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/collaborators{/collaborator}",
        //"teams_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/teams",
        //"hooks_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/hooks",
        //"issue_events_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/issues/events{/number}",
        //"events_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/events",
        //"assignees_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/assignees{/user}",
        //"branches_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/branches{/branch}",
        //"tags_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/tags",
        //"blobs_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/git/blobs{/sha}",
        //"git_tags_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/git/tags{/sha}",
        //"git_refs_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/git/refs{/sha}",
        //"trees_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/git/trees{/sha}",
        //"statuses_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/statuses/{sha}",
        //"languages_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/languages",
        //"stargazers_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/stargazers",
        //"contributors_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/contributors",
        //"subscribers_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/subscribers",
        //"subscription_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/subscription",
        //"commits_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/commits{/sha}",
        //"git_commits_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/git/commits{/sha}",
        //"comments_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/comments{/number}",
        //"issue_comment_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/issues/comments{/number}",
        //"contents_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/contents/{+path}",
        //"compare_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/compare/{base}...{head}",
        //"merges_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/merges",
        //"archive_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/{archive_format}{/ref}",
        //"downloads_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/downloads",
        //"issues_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/issues{/number}",
        //"pulls_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/pulls{/number}",
        //"milestones_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/milestones{/number}",
        //"notifications_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/notifications{?since,all,participating}",
        //"labels_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/labels{/name}",
        //"releases_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/releases{/id}",
        //"deployments_url": "https://api.github.com/repos/SwiftBlogDe/alcatraz-packages/deployments",
        //"created_at": "2015-07-10T22:16:33Z",
        //"updated_at": "2015-07-10T22:16:33Z",
        //"pushed_at": "2015-07-10T22:19:54Z",
        //"git_url": "git://github.com/SwiftBlogDe/alcatraz-packages.git",
        //"ssh_url": "git@github.com:SwiftBlogDe/alcatraz-packages.git",
        //"clone_url": "https://github.com/SwiftBlogDe/alcatraz-packages.git",
        //"svn_url": "https://github.com/SwiftBlogDe/alcatraz-packages",
        //"homepage": "alcatraz.io",
        //"size": 754,
        //"stargazers_count": 0,
        //"watchers_count": 0,
        //"language": "Ruby",
        //"has_issues": false,
        //"has_downloads": true,
        //"has_wiki": true,
        //"has_pages": false,
        //"forks_count": 0,
        //"mirror_url": null,
        //"open_issues_count": 0,
        //"forks": 0,
        //"open_issues": 0,
        //"watchers": 0,
        //"default_branch": "master"
    //},
    //{
        //"id": 38896817,
        //"name": "MarioMeetsMenuBar",
        //"full_name": "SwiftBlogDe/MarioMeetsMenuBar",
        //"owner": {
            //"login": "SwiftBlogDe",
            //"id": 7798434,
            //"avatar_url": "https://avatars.githubusercontent.com/u/7798434?v=3",
            //"gravatar_id": "",
            //"url": "https://api.github.com/users/SwiftBlogDe",
            //"html_url": "https://github.com/SwiftBlogDe",
            //"followers_url": "https://api.github.com/users/SwiftBlogDe/followers",
            //"following_url": "https://api.github.com/users/SwiftBlogDe/following{/other_user}",
            //"gists_url": "https://api.github.com/users/SwiftBlogDe/gists{/gist_id}",
            //"starred_url": "https://api.github.com/users/SwiftBlogDe/starred{/owner}{/repo}",
            //"subscriptions_url": "https://api.github.com/users/SwiftBlogDe/subscriptions",
            //"organizations_url": "https://api.github.com/users/SwiftBlogDe/orgs",
            //"repos_url": "https://api.github.com/users/SwiftBlogDe/repos",
            //"events_url": "https://api.github.com/users/SwiftBlogDe/events{/privacy}",
            //"received_events_url": "https://api.github.com/users/SwiftBlogDe/received_events",
            //"type": "Organization",
            //"site_admin": false
        //},
        //"private": false,
        //"html_url": "https://github.com/SwiftBlogDe/MarioMeetsMenuBar",
        //"description": "A little UI enhancement inspired by bisqwit's E editor for OS X. ",
        //"fork": false,
        //"url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar",
        //"forks_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/forks",
        //"keys_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/keys{/key_id}",
        //"collaborators_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/collaborators{/collaborator}",
        //"teams_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/teams",
        //"hooks_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/hooks",
        //"issue_events_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/issues/events{/number}",
        //"events_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/events",
        //"assignees_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/assignees{/user}",
        //"branches_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/branches{/branch}",
        //"tags_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/tags",
        //"blobs_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/git/blobs{/sha}",
        //"git_tags_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/git/tags{/sha}",
        //"git_refs_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/git/refs{/sha}",
        //"trees_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/git/trees{/sha}",
        //"statuses_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/statuses/{sha}",
        //"languages_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/languages",
        //"stargazers_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/stargazers",
        //"contributors_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/contributors",
        //"subscribers_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/subscribers",
        //"subscription_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/subscription",
        //"commits_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/commits{/sha}",
        //"git_commits_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/git/commits{/sha}",
        //"comments_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/comments{/number}",
        //"issue_comment_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/issues/comments{/number}",
        //"contents_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/contents/{+path}",
        //"compare_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/compare/{base}...{head}",
        //"merges_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/merges",
        //"archive_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/{archive_format}{/ref}",
        //"downloads_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/downloads",
        //"issues_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/issues{/number}",
        //"pulls_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/pulls{/number}",
        //"milestones_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/milestones{/number}",
        //"notifications_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/notifications{?since,all,participating}",
        //"labels_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/labels{/name}",
        //"releases_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/releases{/id}",
        //"deployments_url": "https://api.github.com/repos/SwiftBlogDe/MarioMeetsMenuBar/deployments",
        //"created_at": "2015-07-10T18:51:11Z",
        //"updated_at": "2015-11-20T21:11:01Z",
        //"pushed_at": "2015-07-14T14:55:27Z",
        //"git_url": "git://github.com/SwiftBlogDe/MarioMeetsMenuBar.git",
        //"ssh_url": "git@github.com:SwiftBlogDe/MarioMeetsMenuBar.git",
        //"clone_url": "https://github.com/SwiftBlogDe/MarioMeetsMenuBar.git",
        //"svn_url": "https://github.com/SwiftBlogDe/MarioMeetsMenuBar",
        //"homepage": null,
        //"size": 1164,
        //"stargazers_count": 4,
        //"watchers_count": 4,
        //"language": "Swift",
        //"has_issues": true,
        //"has_downloads": true,
        //"has_wiki": false,
        //"has_pages": true,
        //"forks_count": 0,
        //"mirror_url": null,
        //"open_issues_count": 0,
        //"forks": 0,
        //"open_issues": 0,
        //"watchers": 4,
        //"default_branch": "master"
    //},
    //{
        //"id": 38897287,
        //"name": "retro-xcode-theme",
        //"full_name": "SwiftBlogDe/retro-xcode-theme",
        //"owner": {
            //"login": "SwiftBlogDe",
            //"id": 7798434,
            //"avatar_url": "https://avatars.githubusercontent.com/u/7798434?v=3",
            //"gravatar_id": "",
            //"url": "https://api.github.com/users/SwiftBlogDe",
            //"html_url": "https://github.com/SwiftBlogDe",
            //"followers_url": "https://api.github.com/users/SwiftBlogDe/followers",
            //"following_url": "https://api.github.com/users/SwiftBlogDe/following{/other_user}",
            //"gists_url": "https://api.github.com/users/SwiftBlogDe/gists{/gist_id}",
            //"starred_url": "https://api.github.com/users/SwiftBlogDe/starred{/owner}{/repo}",
            //"subscriptions_url": "https://api.github.com/users/SwiftBlogDe/subscriptions",
            //"organizations_url": "https://api.github.com/users/SwiftBlogDe/orgs",
            //"repos_url": "https://api.github.com/users/SwiftBlogDe/repos",
            //"events_url": "https://api.github.com/users/SwiftBlogDe/events{/privacy}",
            //"received_events_url": "https://api.github.com/users/SwiftBlogDe/received_events",
            //"type": "Organization",
            //"site_admin": false
        //},
        //"private": false,
        //"html_url": "https://github.com/SwiftBlogDe/retro-xcode-theme",
        //"description": "A DOS like xcode theme",
        //"fork": false,
        //"url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme",
        //"forks_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/forks",
        //"keys_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/keys{/key_id}",
        //"collaborators_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/collaborators{/collaborator}",
        //"teams_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/teams",
        //"hooks_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/hooks",
        //"issue_events_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/issues/events{/number}",
        //"events_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/events",
        //"assignees_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/assignees{/user}",
        //"branches_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/branches{/branch}",
        //"tags_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/tags",
        //"blobs_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/git/blobs{/sha}",
        //"git_tags_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/git/tags{/sha}",
        //"git_refs_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/git/refs{/sha}",
        //"trees_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/git/trees{/sha}",
        //"statuses_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/statuses/{sha}",
        //"languages_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/languages",
        //"stargazers_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/stargazers",
        //"contributors_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/contributors",
        //"subscribers_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/subscribers",
        //"subscription_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/subscription",
        //"commits_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/commits{/sha}",
        //"git_commits_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/git/commits{/sha}",
        //"comments_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/comments{/number}",
        //"issue_comment_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/issues/comments{/number}",
        //"contents_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/contents/{+path}",
        //"compare_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/compare/{base}...{head}",
        //"merges_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/merges",
        //"archive_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/{archive_format}{/ref}",
        //"downloads_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/downloads",
        //"issues_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/issues{/number}",
        //"pulls_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/pulls{/number}",
        //"milestones_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/milestones{/number}",
        //"notifications_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/notifications{?since,all,participating}",
        //"labels_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/labels{/name}",
        //"releases_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/releases{/id}",
        //"deployments_url": "https://api.github.com/repos/SwiftBlogDe/retro-xcode-theme/deployments",
        //"created_at": "2015-07-10T19:02:10Z",
        //"updated_at": "2015-12-29T00:36:06Z",
        //"pushed_at": "2015-11-16T09:57:24Z",
        //"git_url": "git://github.com/SwiftBlogDe/retro-xcode-theme.git",
        //"ssh_url": "git@github.com:SwiftBlogDe/retro-xcode-theme.git",
        //"clone_url": "https://github.com/SwiftBlogDe/retro-xcode-theme.git",
        //"svn_url": "https://github.com/SwiftBlogDe/retro-xcode-theme",
        //"homepage": null,
        //"size": 1276,
        //"stargazers_count": 1,
        //"watchers_count": 1,
        //"language": "Shell",
        //"has_issues": true,
        //"has_downloads": true,
        //"has_wiki": true,
        //"has_pages": true,
        //"forks_count": 1,
        //"mirror_url": null,
        //"open_issues_count": 0,
        //"forks": 1,
        //"open_issues": 0,
        //"watchers": 1,
        //"default_branch": "master"
    //}
//]
